### ISSUE TITLE
Use static properties in the class itself

### ISSUE THREAD

**Issue by plorent** [gigafied/minion#6]
I want to define application constants (to avoid using strings for events all over the place) and am using the __static object. But, it seems that I cannot use these static properties in the class where I've defined the __static object?

**Comment by gigafied** [comment]
There are a couple of things you can do here.

One is to define your static object in a closure, then reference it rather than declare it inline. The other is to use minion.get(), both methods are illustrated here:

https://gist.github.com/3201263

Maybe exposing `this.__static` would ideal, I can look into that.

**Comment by gigafied** [comment]
One more thing that works (probably the most elegant):

`this.constructor.SOME_PROP`

I've updated the gist to include that as well.
